const githubData = """{
    "total_count": 233,
    "incomplete_results": false,
    "items": [
        {
            "login": "maiara",
            "id": 227000,
            "node_id": "MDQ6VXNlcjIyNzAwMA==",
            "avatar_url": "https://avatars.githubusercontent.com/u/227000?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiara",
            "html_url": "https://github.com/maiara",
            "followers_url": "https://api.github.com/users/maiara/followers",
            "following_url": "https://api.github.com/users/maiara/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiara/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiara/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiara/subscriptions",
            "organizations_url": "https://api.github.com/users/maiara/orgs",
            "repos_url": "https://api.github.com/users/maiara/repos",
            "events_url": "https://api.github.com/users/maiara/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiara/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraM",
            "id": 40842310,
            "node_id": "MDQ6VXNlcjQwODQyMzEw",
            "avatar_url": "https://avatars.githubusercontent.com/u/40842310?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraM",
            "html_url": "https://github.com/MaiaraM",
            "followers_url": "https://api.github.com/users/MaiaraM/followers",
            "following_url": "https://api.github.com/users/MaiaraM/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraM/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraM/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraM/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraM/orgs",
            "repos_url": "https://api.github.com/users/MaiaraM/repos",
            "events_url": "https://api.github.com/users/MaiaraM/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraM/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraEvangelista",
            "id": 73202320,
            "node_id": "MDQ6VXNlcjczMjAyMzIw",
            "avatar_url": "https://avatars.githubusercontent.com/u/73202320?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraEvangelista",
            "html_url": "https://github.com/MaiaraEvangelista",
            "followers_url": "https://api.github.com/users/MaiaraEvangelista/followers",
            "following_url": "https://api.github.com/users/MaiaraEvangelista/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraEvangelista/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraEvangelista/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraEvangelista/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraEvangelista/orgs",
            "repos_url": "https://api.github.com/users/MaiaraEvangelista/repos",
            "events_url": "https://api.github.com/users/MaiaraEvangelista/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraEvangelista/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maihe",
            "id": 2921416,
            "node_id": "MDQ6VXNlcjI5MjE0MTY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2921416?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maihe",
            "html_url": "https://github.com/maihe",
            "followers_url": "https://api.github.com/users/maihe/followers",
            "following_url": "https://api.github.com/users/maihe/following{/other_user}",
            "gists_url": "https://api.github.com/users/maihe/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maihe/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maihe/subscriptions",
            "organizations_url": "https://api.github.com/users/maihe/orgs",
            "repos_url": "https://api.github.com/users/maihe/repos",
            "events_url": "https://api.github.com/users/maihe/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maihe/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiaraborges",
            "id": 36283648,
            "node_id": "MDQ6VXNlcjM2MjgzNjQ4",
            "avatar_url": "https://avatars.githubusercontent.com/u/36283648?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiaraborges",
            "html_url": "https://github.com/maiaraborges",
            "followers_url": "https://api.github.com/users/maiaraborges/followers",
            "following_url": "https://api.github.com/users/maiaraborges/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiaraborges/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiaraborges/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiaraborges/subscriptions",
            "organizations_url": "https://api.github.com/users/maiaraborges/orgs",
            "repos_url": "https://api.github.com/users/maiaraborges/repos",
            "events_url": "https://api.github.com/users/maiaraborges/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiaraborges/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiarar",
            "id": 15115197,
            "node_id": "MDQ6VXNlcjE1MTE1MTk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/15115197?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiarar",
            "html_url": "https://github.com/maiarar",
            "followers_url": "https://api.github.com/users/maiarar/followers",
            "following_url": "https://api.github.com/users/maiarar/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiarar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiarar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiarar/subscriptions",
            "organizations_url": "https://api.github.com/users/maiarar/orgs",
            "repos_url": "https://api.github.com/users/maiarar/repos",
            "events_url": "https://api.github.com/users/maiarar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiarar/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraRodrigues",
            "id": 59736461,
            "node_id": "MDQ6VXNlcjU5NzM2NDYx",
            "avatar_url": "https://avatars.githubusercontent.com/u/59736461?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraRodrigues",
            "html_url": "https://github.com/MaiaraRodrigues",
            "followers_url": "https://api.github.com/users/MaiaraRodrigues/followers",
            "following_url": "https://api.github.com/users/MaiaraRodrigues/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraRodrigues/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraRodrigues/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraRodrigues/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraRodrigues/orgs",
            "repos_url": "https://api.github.com/users/MaiaraRodrigues/repos",
            "events_url": "https://api.github.com/users/MaiaraRodrigues/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraRodrigues/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraSantos",
            "id": 22840186,
            "node_id": "MDQ6VXNlcjIyODQwMTg2",
            "avatar_url": "https://avatars.githubusercontent.com/u/22840186?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraSantos",
            "html_url": "https://github.com/MaiaraSantos",
            "followers_url": "https://api.github.com/users/MaiaraSantos/followers",
            "following_url": "https://api.github.com/users/MaiaraSantos/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraSantos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraSantos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraSantos/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraSantos/orgs",
            "repos_url": "https://api.github.com/users/MaiaraSantos/repos",
            "events_url": "https://api.github.com/users/MaiaraSantos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraSantos/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraFarias",
            "id": 42505752,
            "node_id": "MDQ6VXNlcjQyNTA1NzUy",
            "avatar_url": "https://avatars.githubusercontent.com/u/42505752?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraFarias",
            "html_url": "https://github.com/MaiaraFarias",
            "followers_url": "https://api.github.com/users/MaiaraFarias/followers",
            "following_url": "https://api.github.com/users/MaiaraFarias/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraFarias/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraFarias/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraFarias/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraFarias/orgs",
            "repos_url": "https://api.github.com/users/MaiaraFarias/repos",
            "events_url": "https://api.github.com/users/MaiaraFarias/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraFarias/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiarafa10",
            "id": 16249040,
            "node_id": "MDQ6VXNlcjE2MjQ5MDQw",
            "avatar_url": "https://avatars.githubusercontent.com/u/16249040?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiarafa10",
            "html_url": "https://github.com/maiarafa10",
            "followers_url": "https://api.github.com/users/maiarafa10/followers",
            "following_url": "https://api.github.com/users/maiarafa10/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiarafa10/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiarafa10/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiarafa10/subscriptions",
            "organizations_url": "https://api.github.com/users/maiarafa10/orgs",
            "repos_url": "https://api.github.com/users/maiarafa10/repos",
            "events_url": "https://api.github.com/users/maiarafa10/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiarafa10/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "mgbatista",
            "id": 68406558,
            "node_id": "MDQ6VXNlcjY4NDA2NTU4",
            "avatar_url": "https://avatars.githubusercontent.com/u/68406558?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mgbatista",
            "html_url": "https://github.com/mgbatista",
            "followers_url": "https://api.github.com/users/mgbatista/followers",
            "following_url": "https://api.github.com/users/mgbatista/following{/other_user}",
            "gists_url": "https://api.github.com/users/mgbatista/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mgbatista/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mgbatista/subscriptions",
            "organizations_url": "https://api.github.com/users/mgbatista/orgs",
            "repos_url": "https://api.github.com/users/mgbatista/repos",
            "events_url": "https://api.github.com/users/mgbatista/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mgbatista/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraLeda",
            "id": 49168491,
            "node_id": "MDQ6VXNlcjQ5MTY4NDkx",
            "avatar_url": "https://avatars.githubusercontent.com/u/49168491?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraLeda",
            "html_url": "https://github.com/MaiaraLeda",
            "followers_url": "https://api.github.com/users/MaiaraLeda/followers",
            "following_url": "https://api.github.com/users/MaiaraLeda/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraLeda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraLeda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraLeda/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraLeda/orgs",
            "repos_url": "https://api.github.com/users/MaiaraLeda/repos",
            "events_url": "https://api.github.com/users/MaiaraLeda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraLeda/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiaraborsatti",
            "id": 78621880,
            "node_id": "MDQ6VXNlcjc4NjIxODgw",
            "avatar_url": "https://avatars.githubusercontent.com/u/78621880?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiaraborsatti",
            "html_url": "https://github.com/maiaraborsatti",
            "followers_url": "https://api.github.com/users/maiaraborsatti/followers",
            "following_url": "https://api.github.com/users/maiaraborsatti/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiaraborsatti/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiaraborsatti/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiaraborsatti/subscriptions",
            "organizations_url": "https://api.github.com/users/maiaraborsatti/orgs",
            "repos_url": "https://api.github.com/users/maiaraborsatti/repos",
            "events_url": "https://api.github.com/users/maiaraborsatti/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiaraborsatti/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "arienemaiara",
            "id": 5312296,
            "node_id": "MDQ6VXNlcjUzMTIyOTY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5312296?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/arienemaiara",
            "html_url": "https://github.com/arienemaiara",
            "followers_url": "https://api.github.com/users/arienemaiara/followers",
            "following_url": "https://api.github.com/users/arienemaiara/following{/other_user}",
            "gists_url": "https://api.github.com/users/arienemaiara/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/arienemaiara/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/arienemaiara/subscriptions",
            "organizations_url": "https://api.github.com/users/arienemaiara/orgs",
            "repos_url": "https://api.github.com/users/arienemaiara/repos",
            "events_url": "https://api.github.com/users/arienemaiara/events{/privacy}",
            "received_events_url": "https://api.github.com/users/arienemaiara/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiaralange",
            "id": 28520569,
            "node_id": "MDQ6VXNlcjI4NTIwNTY5",
            "avatar_url": "https://avatars.githubusercontent.com/u/28520569?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiaralange",
            "html_url": "https://github.com/maiaralange",
            "followers_url": "https://api.github.com/users/maiaralange/followers",
            "following_url": "https://api.github.com/users/maiaralange/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiaralange/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiaralange/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiaralange/subscriptions",
            "organizations_url": "https://api.github.com/users/maiaralange/orgs",
            "repos_url": "https://api.github.com/users/maiaralange/repos",
            "events_url": "https://api.github.com/users/maiaralange/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiaralange/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiws",
            "id": 25993071,
            "node_id": "MDQ6VXNlcjI1OTkzMDcx",
            "avatar_url": "https://avatars.githubusercontent.com/u/25993071?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiws",
            "html_url": "https://github.com/maiws",
            "followers_url": "https://api.github.com/users/maiws/followers",
            "following_url": "https://api.github.com/users/maiws/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiws/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiws/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiws/subscriptions",
            "organizations_url": "https://api.github.com/users/maiws/orgs",
            "repos_url": "https://api.github.com/users/maiws/repos",
            "events_url": "https://api.github.com/users/maiws/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiws/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraGoldacker",
            "id": 29411848,
            "node_id": "MDQ6VXNlcjI5NDExODQ4",
            "avatar_url": "https://avatars.githubusercontent.com/u/29411848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraGoldacker",
            "html_url": "https://github.com/MaiaraGoldacker",
            "followers_url": "https://api.github.com/users/MaiaraGoldacker/followers",
            "following_url": "https://api.github.com/users/MaiaraGoldacker/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraGoldacker/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraGoldacker/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraGoldacker/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraGoldacker/orgs",
            "repos_url": "https://api.github.com/users/MaiaraGoldacker/repos",
            "events_url": "https://api.github.com/users/MaiaraGoldacker/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraGoldacker/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "IT-maiara-costa",
            "id": 45687654,
            "node_id": "MDQ6VXNlcjQ1Njg3NjU0",
            "avatar_url": "https://avatars.githubusercontent.com/u/45687654?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/IT-maiara-costa",
            "html_url": "https://github.com/IT-maiara-costa",
            "followers_url": "https://api.github.com/users/IT-maiara-costa/followers",
            "following_url": "https://api.github.com/users/IT-maiara-costa/following{/other_user}",
            "gists_url": "https://api.github.com/users/IT-maiara-costa/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/IT-maiara-costa/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/IT-maiara-costa/subscriptions",
            "organizations_url": "https://api.github.com/users/IT-maiara-costa/orgs",
            "repos_url": "https://api.github.com/users/IT-maiara-costa/repos",
            "events_url": "https://api.github.com/users/IT-maiara-costa/events{/privacy}",
            "received_events_url": "https://api.github.com/users/IT-maiara-costa/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiaracoelho",
            "id": 3943933,
            "node_id": "MDQ6VXNlcjM5NDM5MzM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3943933?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiaracoelho",
            "html_url": "https://github.com/maiaracoelho",
            "followers_url": "https://api.github.com/users/maiaracoelho/followers",
            "following_url": "https://api.github.com/users/maiaracoelho/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiaracoelho/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiaracoelho/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiaracoelho/subscriptions",
            "organizations_url": "https://api.github.com/users/maiaracoelho/orgs",
            "repos_url": "https://api.github.com/users/maiaracoelho/repos",
            "events_url": "https://api.github.com/users/maiaracoelho/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiaracoelho/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MayRegis",
            "id": 38231397,
            "node_id": "MDQ6VXNlcjM4MjMxMzk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/38231397?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MayRegis",
            "html_url": "https://github.com/MayRegis",
            "followers_url": "https://api.github.com/users/MayRegis/followers",
            "following_url": "https://api.github.com/users/MayRegis/following{/other_user}",
            "gists_url": "https://api.github.com/users/MayRegis/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MayRegis/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MayRegis/subscriptions",
            "organizations_url": "https://api.github.com/users/MayRegis/orgs",
            "repos_url": "https://api.github.com/users/MayRegis/repos",
            "events_url": "https://api.github.com/users/MayRegis/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MayRegis/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiFaria",
            "id": 52571069,
            "node_id": "MDQ6VXNlcjUyNTcxMDY5",
            "avatar_url": "https://avatars.githubusercontent.com/u/52571069?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiFaria",
            "html_url": "https://github.com/MaiFaria",
            "followers_url": "https://api.github.com/users/MaiFaria/followers",
            "following_url": "https://api.github.com/users/MaiFaria/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiFaria/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiFaria/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiFaria/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiFaria/orgs",
            "repos_url": "https://api.github.com/users/MaiFaria/repos",
            "events_url": "https://api.github.com/users/MaiFaria/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiFaria/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "m-schein",
            "id": 68960818,
            "node_id": "MDQ6VXNlcjY4OTYwODE4",
            "avatar_url": "https://avatars.githubusercontent.com/u/68960818?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/m-schein",
            "html_url": "https://github.com/m-schein",
            "followers_url": "https://api.github.com/users/m-schein/followers",
            "following_url": "https://api.github.com/users/m-schein/following{/other_user}",
            "gists_url": "https://api.github.com/users/m-schein/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/m-schein/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/m-schein/subscriptions",
            "organizations_url": "https://api.github.com/users/m-schein/orgs",
            "repos_url": "https://api.github.com/users/m-schein/repos",
            "events_url": "https://api.github.com/users/m-schein/events{/privacy}",
            "received_events_url": "https://api.github.com/users/m-schein/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiarawill",
            "id": 50561516,
            "node_id": "MDQ6VXNlcjUwNTYxNTE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/50561516?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiarawill",
            "html_url": "https://github.com/maiarawill",
            "followers_url": "https://api.github.com/users/maiarawill/followers",
            "following_url": "https://api.github.com/users/maiarawill/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiarawill/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiarawill/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiarawill/subscriptions",
            "organizations_url": "https://api.github.com/users/maiarawill/orgs",
            "repos_url": "https://api.github.com/users/maiarawill/repos",
            "events_url": "https://api.github.com/users/maiarawill/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiarawill/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraB",
            "id": 8663340,
            "node_id": "MDQ6VXNlcjg2NjMzNDA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8663340?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraB",
            "html_url": "https://github.com/MaiaraB",
            "followers_url": "https://api.github.com/users/MaiaraB/followers",
            "following_url": "https://api.github.com/users/MaiaraB/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraB/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraB/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraB/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraB/orgs",
            "repos_url": "https://api.github.com/users/MaiaraB/repos",
            "events_url": "https://api.github.com/users/MaiaraB/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraB/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "claymaiara",
            "id": 7199836,
            "node_id": "MDQ6VXNlcjcxOTk4MzY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7199836?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/claymaiara",
            "html_url": "https://github.com/claymaiara",
            "followers_url": "https://api.github.com/users/claymaiara/followers",
            "following_url": "https://api.github.com/users/claymaiara/following{/other_user}",
            "gists_url": "https://api.github.com/users/claymaiara/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/claymaiara/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/claymaiara/subscriptions",
            "organizations_url": "https://api.github.com/users/claymaiara/orgs",
            "repos_url": "https://api.github.com/users/claymaiara/repos",
            "events_url": "https://api.github.com/users/claymaiara/events{/privacy}",
            "received_events_url": "https://api.github.com/users/claymaiara/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "Maiara99",
            "id": 64428720,
            "node_id": "MDQ6VXNlcjY0NDI4NzIw",
            "avatar_url": "https://avatars.githubusercontent.com/u/64428720?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Maiara99",
            "html_url": "https://github.com/Maiara99",
            "followers_url": "https://api.github.com/users/Maiara99/followers",
            "following_url": "https://api.github.com/users/Maiara99/following{/other_user}",
            "gists_url": "https://api.github.com/users/Maiara99/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Maiara99/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Maiara99/subscriptions",
            "organizations_url": "https://api.github.com/users/Maiara99/orgs",
            "repos_url": "https://api.github.com/users/Maiara99/repos",
            "events_url": "https://api.github.com/users/Maiara99/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Maiara99/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maiara-sassi",
            "id": 16891209,
            "node_id": "MDQ6VXNlcjE2ODkxMjA5",
            "avatar_url": "https://avatars.githubusercontent.com/u/16891209?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maiara-sassi",
            "html_url": "https://github.com/maiara-sassi",
            "followers_url": "https://api.github.com/users/maiara-sassi/followers",
            "following_url": "https://api.github.com/users/maiara-sassi/following{/other_user}",
            "gists_url": "https://api.github.com/users/maiara-sassi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maiara-sassi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maiara-sassi/subscriptions",
            "organizations_url": "https://api.github.com/users/maiara-sassi/orgs",
            "repos_url": "https://api.github.com/users/maiara-sassi/repos",
            "events_url": "https://api.github.com/users/maiara-sassi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maiara-sassi/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraLopes",
            "id": 73555171,
            "node_id": "MDQ6VXNlcjczNTU1MTcx",
            "avatar_url": "https://avatars.githubusercontent.com/u/73555171?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraLopes",
            "html_url": "https://github.com/MaiaraLopes",
            "followers_url": "https://api.github.com/users/MaiaraLopes/followers",
            "following_url": "https://api.github.com/users/MaiaraLopes/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraLopes/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraLopes/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraLopes/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraLopes/orgs",
            "repos_url": "https://api.github.com/users/MaiaraLopes/repos",
            "events_url": "https://api.github.com/users/MaiaraLopes/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraLopes/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "mgarcia88",
            "id": 18174474,
            "node_id": "MDQ6VXNlcjE4MTc0NDc0",
            "avatar_url": "https://avatars.githubusercontent.com/u/18174474?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mgarcia88",
            "html_url": "https://github.com/mgarcia88",
            "followers_url": "https://api.github.com/users/mgarcia88/followers",
            "following_url": "https://api.github.com/users/mgarcia88/following{/other_user}",
            "gists_url": "https://api.github.com/users/mgarcia88/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mgarcia88/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mgarcia88/subscriptions",
            "organizations_url": "https://api.github.com/users/mgarcia88/orgs",
            "repos_url": "https://api.github.com/users/mgarcia88/repos",
            "events_url": "https://api.github.com/users/mgarcia88/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mgarcia88/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaiaraColombo",
            "id": 70031955,
            "node_id": "MDQ6VXNlcjcwMDMxOTU1",
            "avatar_url": "https://avatars.githubusercontent.com/u/70031955?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaiaraColombo",
            "html_url": "https://github.com/MaiaraColombo",
            "followers_url": "https://api.github.com/users/MaiaraColombo/followers",
            "following_url": "https://api.github.com/users/MaiaraColombo/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaiaraColombo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaiaraColombo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaiaraColombo/subscriptions",
            "organizations_url": "https://api.github.com/users/MaiaraColombo/orgs",
            "repos_url": "https://api.github.com/users/MaiaraColombo/repos",
            "events_url": "https://api.github.com/users/MaiaraColombo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaiaraColombo/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        }
    ]
}""";
